# Generated by Django 5.0.6 on 2024-05-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waybill', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.driver'),
        ),
        migrations.AddField(
            model_name='cargowaybill',
            name='waybill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waybill.waybill'),
        ),
    ]
