# Generated by Django 5.0.6 on 2024-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
