# Generated by Django 5.0.6 on 2024-05-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0003_alter_waybill_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='created_at',
            field=models.DateField(),
        ),
    ]
