# Generated by Django 5.0.6 on 2024-05-28 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybill', '0004_alter_waybill_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargowaybill',
            name='waybill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waybill.waybill'),
        ),
    ]
