# Generated by Django 5.0.6 on 2024-05-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigadier', models.CharField(max_length=50)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brigade.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='workshop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brigade.workshop'),
        ),
    ]
