# Generated by Django 5.0.6 on 2024-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
