# Generated by Django 5.0.6 on 2024-05-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True)),
                ('brand', models.CharField(max_length=50)),
                ('is_decommissioned', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garage.garage')),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliary',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicle.vehicle')),
                ('description', models.CharField(max_length=50)),
            ],
            bases=('vehicle.vehicle',),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicle.vehicle')),
                ('capacity', models.IntegerField()),
            ],
            bases=('vehicle.vehicle',),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicle.vehicle')),
                ('passenger_capacity', models.IntegerField()),
                ('routes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.route')),
            ],
            bases=('vehicle.vehicle',),
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicle.vehicle')),
                ('passenger_capacity', models.IntegerField()),
                ('routes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.route')),
            ],
            bases=('vehicle.vehicle',),
        ),
    ]
