# Generated by Django 5.0.6 on 2024-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_routes_bus_route_rename_routes_taxi_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='modified_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
