# Generated by Django 5.0.6 on 2024-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='modified_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
