# Generated by Django 5.0.6 on 2024-05-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='modified_at',
            field=models.DateField(),
        ),
    ]
