# Generated by Django 5.0.6 on 2024-05-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_worker_created_at_alter_worker_modified_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terchnician',
            new_name='Technician',
        ),
    ]
